demo/demo/urls.py
from django.urls import path
from . import views, APIViews

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path(
        'recipe/create/',
        APIViews.RecipeCreateView.as_view(),
        name='recipe-create'
        ),
    path(
        'recipe/update/<int:pk>/',
        APIViews.RecipeUpdateView.as_view(),
        name='recipe-update'
        ),
    path(
        'recipe/delete/<int:pk>/',
        APIViews.RecipeDeleteView.as_view(),
        name='recipe-delete'
        ),
    
]

demo/demo/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

from x_django_app.models import XModel


class Recipe(models.Model, XModel):
    '''
    Model for Recipes
    '''
    name = models.CharField(
                        verbose_name=_('Name'),
                        max_length=128,
                        unique=True,
                        blank=False,
                        null=False
    )
    description = models.CharField(
                        verbose_name=_('Description'),
                        max_length=255,
                        blank=False,
                        null=False
    )
    created_at = models.DateTimeField(
                        verbose_name=_('Created at'),
                        auto_now_add=True,
                        blank=False
    )

    def __str__(self):
        '''
        String representation
        '''
        return self.name


class Item(models.Model, XModel):
    '''
    Model for recipe's items
    '''
    recipe = models.ForeignKey(
                        'Recipe',
                        verbose_name=_('Recipe'),
                        related_name='item_recipe',
                        on_delete=models.CASCADE,
                        blank=True,
                        null=True
    )
    name = models.CharField(
                        verbose_name=_('Name'),
                        max_length=128,
                        unique=False,
                        blank=False,
                        null=False
    )
    quantity = models.IntegerField(
                        verbose_name=_('Quantity'),
                        unique=False,
                        blank=False,
                        null=False
    )
    created_at = models.DateTimeField(
                        verbose_name=_('Created at'),
                        auto_now_add=True,
                        blank=False
    )


    def __str__(self):
        '''
        String representation
        '''
        return f"{self.recipe.name}-{self.name}"

demo/demo/forms.py
from django import forms
from . import models


class RecipeForm(forms.ModelForm):
    '''
    Recipe's form
    '''

    class Meta:
        model = models.Recipe
        fields = ['name', 'description']


class ItemForm(forms.ModelForm):
    '''
    Item's form
    '''

    class Meta:
        model = models.Item
        fields = ['recipe', 'name', 'quantity']

demo/demo/views.py
from . import models
from x_django_app.views import XListView


class Index(XListView):
    '''
    Index page for recipes and items
    '''
    template_name = 'demo/index.html'
    model = models.Recipe
    search_fields = ['name', 'description']
    queryset = models.Recipe.objects.all()
    ordering = ('name', 'description')
    paginate_by = 20

demo/demo/templates/demo/index.html
{% load static %}
{% load crispy_forms_tags %}
{% load i18n %}
{% load x_tags %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Demo project</title>
    <!-- Bootstrap -->
    <script
          src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
          integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
          crossorigin="anonymous"></script>
    <script
          src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
          integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
          crossorigin="anonymous"></script>
    <link
          rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
          crossorigin="anonymous">
    <script
          src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
          integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
          crossorigin="anonymous"></script>

    <!-- font awesome 5 css -->
    <link
      rel="stylesheet"
      href="https://use.fontawesome.com/releases/v5.6.3/css/all.css"
      integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/"
      crossorigin="anonymous">

    <!--MAIN STYLE-->
    <link
      href="{% static 'demo/style.css' %}"
      rel="stylesheet"
      type="text/css">

  </head>
  <body>
    <div class="container">
      <br>
      <h1 class="text-center">Demo Project</h1>
      <hr>
      <br>
      <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <input class="btn btn-primary" type="submit" value="{% trans 'Search' %}">
      </form>
      <hr>
      <table class="table table-striped table-sm">
        <tbody>
          <tr>
            <th scope="row">
              <a
                href="{% x_sort sort 'name' %}">
                {% trans 'Name' %}
              </a>
            </th>
            <td>
              <strong>
                <a href="{% x_sort sort 'description' %}">
                  {% trans 'Description' %}
                </a>
              </strong>
            </td>
            <td>
              <strong>
                <a href="{% x_sort sort 'created_at' %}">
                  {% trans 'Created at' %}
                </a>
              </strong>
            </td>
          </tr>
        {% for recipe in recipe_list %}
          <tr class="table-row">
            <th scope="row">
              {{ recipe.name }}
            </th>
            <td>
              {{ recipe.description }}
            </td>
            <td>
              {{ recipe.created_at }}
            </td>
          </tr>
          {% empty %}
          <tr>
            <th scope="row">{% trans 'No recipes found' %}</th>
          </tr>
          {% endfor %}
        </tbody>
      </table>
      {% include 'x_django_app/_pagination.html' %}
    </div>
  </body>
</html>